# Generated by Django 5.2.12 on 2026-03-09 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('board', models.CharField(choices=[('RBSE', 'RBSE'), ('RTU', 'RTU'), ('CBSE', 'CBSE')], default='RBSE', max_length=10)),
                ('class_name', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('balanced', 'Balanced'), ('hard', 'Hard')], default='balanced', max_length=20)),
                ('topics', models.TextField(blank=True, help_text='Comma separated custom topics')),
                ('adhere_marking_scheme', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paper_content', models.JSONField(blank=True, null=True)),
                ('answer_key', models.JSONField(blank=True, null=True)),
                ('paper_text', models.TextField(blank=True)),
                ('answer_key_text', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='papers/')),
                ('credits_used', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
